apiVersion: apps/v1
kind: Deployment
metadata:
  name: en-pt
  namespace: sidecar
spec:
  replicas: 2
  selector:
    matchLabels:
      app: en-pt
  template:
    metadata:
      labels:
        app: en-pt
    spec:
      containers:
        - name: en-pt
          image: localhost:32000/sidecar:latest
          imagePullPolicy: Always
          args:
            - '/app/web'
          ports:
            - name: web-port
              containerPort: 8080
          resources:
            limits:
              cpu: "2.0"
              memory: 100Mi
              ephemeral-storage: 1Gi
            requests:
              cpu: "1"
              memory: 100Mi
              ephemeral-storage: 1Gi
        - name: sidecar
          image: localhost:32000/sidecar:latest
          imagePullPolicy: Always
          args:
            - '/app/sidecar'
          env:
            - name: QUEUE_NAME
              value: en-pt
            - name: RABBITMQ_URL
              value: amqp://guest:guest@rabbitmq.storage.svc.cluster.local:5672
            - name: WEB_URL
              value: http://localhost:8080
          resources:
            limits:
              cpu: "2.0"
              memory: 50Mi
            requests:
              cpu: "0.05"
              memory: 50Mi
---
apiVersion: v1
kind: Service
metadata:
  name: en-pt
  namespace: sidecar
spec:
  ports:
    - name: web-port
      port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: en-pt
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: en-pt
  namespace: sidecar
spec:
  scaleTargetRef:
    name: en-pt
  pollingInterval: 5 # Optional. Default: 30 seconds
  cooldownPeriod: 300 # Optional. Default: 300 seconds
  maxReplicaCount: 10 # Optional. Default: 100
  triggers:
    - type: rabbitmq
      metadata:
        queueName: en-pt
        queueLength: "1"
      authenticationRef:
        name: rabbitmq-trigger
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: rabbitmq-trigger
  namespace: sidecar
spec:
  secretTargetRef:
    - parameter: host
      name: rabbitmq-trigger-secret
      key: RabbitMqHost
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-trigger-secret
  namespace: sidecar
data:
  RabbitMqHost: YW1xcDovL2d1ZXN0Omd1ZXN0QHJhYmJpdG1xLnN0b3JhZ2Uuc3ZjLmNsdXN0ZXIubG9jYWw6NTY3Mg==
