apiVersion: apps/v1
kind: Deployment
metadata:
  name: sender
  namespace: sidecar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sender
  template:
    metadata:
      labels:
        app: sender
    spec:
      containers:
        - name: sender
          image: localhost:32000/sidecar:latest
          imagePullPolicy: Always
          args:
            - '/app/sender'
          ports:
            - name: web-port
              containerPort: 8080
          env:
            - name: RABBITMQ_URL
              value: amqp://guest:guest@rabbitmq.storage.svc.cluster.local:5672/
            - name: CALLBACK_URL
              value: http://sender.sidecar.svc.cluster.local
          resources:
            limits:
              cpu: "2.0"
              memory: 500Mi
              ephemeral-storage: 1Gi
            requests:
              cpu: "0.1"
              memory: 50Mi
              ephemeral-storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: sender
  namespace: sidecar
spec:
  ports:
    - name: web-port
      port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: sender
